Repository XRPLF/clio, pull requests merged in 2024-03, with the labels that each got.

#1232 Build docs and upload to gh-pages
  .githooks/check-docs
  .github/workflows/docs.yml
  CMake/ClioVersion.cmake
  CMake/Docs.cmake
  CMakeLists.txt
  docs/CMakeLists.txt
  docs/Doxyfile
Labels: documentation, ci

#1237 Upgrade libxrpl to 2.2.0-b1
  conanfile.py
Labels: compatibility

#1260 Fetch lfs files when generating docs
  .github/workflows/docs.yml
Labels: ci

#1208 [1194] Add instructions on how to generate Doxygen docs
  docs/build-clio.md
  docs/img/doxygen-docs-output.png
Labels: documentation

#1268 Remove mentions of release docs from workflow
  .github/workflows/docs.yml
Labels: ci
